"""
Target Role Definitions and Domain Configuration for NexHire AI
Supports all 6 core engineering & technical roles without hardcoded SDE assumptions.
"""

SUPPORTED_ROLES = [
    "Software Development Engineer (SDE)",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Data Scientist / AI Engineer",
    "DevOps / Cloud Engineer",
]

ROLE_DOMAINS = {
    "Software Development Engineer (SDE)": [
        "DSA & Algorithm Complexity",
        "Object Oriented Programming (OOP)",
        "Database Management Systems (DBMS)",
        "Operating Systems & Concurrency",
        "Computer Networks & Protocols",
        "Core Programming & Memory Management",
        "System Design & Scalability",
    ],
    "Frontend Developer": [
        "HTML5, Semantic UI & Web Standards",
        "CSS3, Responsive Design & Layouts (Flexbox/Grid)",
        "Modern JavaScript (ES6+, Async, DOM APIs)",
        "React & Component Architecture",
        "State Management & Data Flow",
        "Web Performance Optimization & Core Web Vitals",
        "Web Accessibility (a11y) & Cross-Browser Compatibility",
    ],
    "Backend Developer": [
        "Backend Architecture & Frameworks (Node.js/FastAPI/Spring)",
        "RESTful API Design & Best Practices",
        "Database Systems (SQL & NoSQL Query Optimization)",
        "Authentication, Authorization & Security (JWT/OAuth)",
        "Distributed Caching & Message Queues (Redis/Kafka)",
        "Concurrency, Threading & Asynchronous I/O",
        "System Architecture & API Scalability",
    ],
    "Full Stack Developer": [
        "Modern Frontend Architecture (React/Vue/Next.js)",
        "Backend Frameworks & REST APIs",
        "Database Design & ORM/ODM (MongoDB/PostgreSQL)",
        "End-to-End Authentication & State Management",
        "Client-Server Data Flow & WebSockets",
        "Full Stack System Architecture & Deployment",
        "Web Performance & Security Best Practices",
    ],
    "Data Scientist / AI Engineer": [
        "Python for Data Science (NumPy, Pandas)",
        "Statistical Inference & Probability",
        "Machine Learning Algorithms & Model Evaluation",
        "Feature Engineering & Data Preprocessing",
        "Deep Learning Architectures (CNNs, RNNs, Transformers)",
        "Natural Language Processing & Generative AI / LLMs",
        "SQL & Large-Scale Data Handling",
        "MLOps, Model Deployment & Pipeline Monitoring",
    ],
    "DevOps / Cloud Engineer": [
        "Linux System Administration & Shell Scripting",
        "Containerization with Docker",
        "Container Orchestration with Kubernetes",
        "CI/CD Pipelines & Automated Deployments",
        "Cloud Infrastructure (AWS / Azure / GCP)",
        "Infrastructure as Code (Terraform / Ansible)",
        "Networking, DNS, Load Balancing & SSL/TLS",
        "Monitoring, Logging & Observability (Prometheus/Grafana)",
    ],
}

# Skill Normalization Dictionary: standardizes technology variations
SKILL_NORMALIZATION_MAP = {
    "reactjs": "React",
    "react.js": "React",
    "react": "React",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "vue": "Vue.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "node": "Node.js",
    "expressjs": "Express.js",
    "express.js": "Express.js",
    "express": "Express.js",
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "mongo": "MongoDB",
    "mongodb": "MongoDB",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "sql server": "SQL Server",
    "mssql": "SQL Server",
    "redis": "Redis",
    "sklearn": "Scikit-learn",
    "scikit-learn": "Scikit-learn",
    "scikit learn": "Scikit-learn",
    "tf": "TensorFlow",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "keras": "Keras",
    "nlp": "Natural Language Processing (NLP)",
    "cv": "Computer Vision",
    "genai": "Generative AI",
    "generative ai": "Generative AI",
    "llm": "Large Language Models (LLMs)",
    "llms": "Large Language Models (LLMs)",
    "k8s": "Kubernetes",
    "kubernetes": "Kubernetes",
    "docker": "Docker",
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "Google Cloud Platform",
    "azure": "Microsoft Azure",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "linux": "Linux",
    "git": "Git",
    "dsa": "DSA",
    "data structures": "Data Structures",
    "algorithms": "Algorithms",
    "dbms": "DBMS",
    "os": "Operating Systems",
    "operating systems": "Operating Systems",
    "cn": "Computer Networks",
    "computer networks": "Computer Networks",
    "oop": "OOP",
    "oops": "OOP",
    "system design": "System Design",
    "rest api": "REST APIs",
    "rest apis": "REST APIs",
    "graphql": "GraphQL",
    "html": "HTML5",
    "html5": "HTML5",
    "css": "CSS3",
    "css3": "CSS3",
    "tailwind": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "python": "Python",
    "py": "Python",
    "java": "Java",
    "cpp": "C++",
    "c++": "C++",
    "c#": "C#",
    "csharp": "C#",
    "golang": "Go",
    "go": "Go",
    "rust": "Rust",
}

def normalize_skill_name(skill: str) -> str:
    """Normalize a skill name string using canonical lookup or title case fallback"""
    if not skill or not isinstance(skill, str):
        return ""
    cleaned = skill.strip().lower()
    return SKILL_NORMALIZATION_MAP.get(cleaned, skill.strip())
