"""
Target Role Definitions and Domain Configuration for NexHire AI
Supports all 6 core engineering & technical roles without hardcoded SDE assumptions.
"""

SUPPORTED_ROLES = [
    "Software Development Engineer (SDE)",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Data Scientist / AI Engineer",
    "DevOps / Cloud Engineer",
]

ROLE_DOMAINS = {
    "Software Development Engineer (SDE)": [
        "DSA",
        "OOP",
        "DBMS",
        "OS",
        "Computer Networks",
        "Programming",
        "System Design"
    ],
    "Frontend Developer": [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Web Performance",
        "Accessibility"
    ],
    "Backend Developer": [
        "Programming",
        "REST APIs",
        "Databases",
        "Authentication",
        "Backend Architecture",
        "System Design"
    ],
    "Full Stack Developer": [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Backend",
        "REST APIs",
        "MongoDB",
        "SQL",
        "Authentication",
        "System Design"
    ],
    "Data Scientist / AI Engineer": [
        "Python",
        "Statistics",
        "SQL",
        "Pandas",
        "NumPy",
        "Machine Learning",
        "Deep Learning",
        "NLP",
        "Computer Vision",
        "Generative AI"
    ],
    "DevOps / Cloud Engineer": [
        "Linux",
        "Git",
        "Docker",
        "CI/CD",
        "AWS",
        "Azure",
        "Kubernetes",
        "Networking",
        "Monitoring"
    ]
}

# Skill Normalization Dictionary: standardizes technology variations
SKILL_NORMALIZATION_MAP = {
    "reactjs": "React",
    "react.js": "React",
    "react js": "React",
    "react": "React",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "next js": "Next.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "vue js": "Vue.js",
    "vue": "Vue.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "node js": "Node.js",
    "node": "Node.js",
    "expressjs": "Express.js",
    "express.js": "Express.js",
    "express js": "Express.js",
    "express": "Express.js",
    "fastapi": "FastAPI",
    "fast api": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "mongo": "MongoDB",
    "mongodb": "MongoDB",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "sql server": "SQL Server",
    "mssql": "SQL Server",
    "redis": "Redis",
    "sklearn": "Scikit-learn",
    "scikit-learn": "Scikit-learn",
    "scikit learn": "Scikit-learn",
    "random forest": "Random Forest",
    "randomforest": "Random Forest",
    "decision tree": "Decision Trees",
    "decision trees": "Decision Trees",
    "gradient boosting": "Gradient Boosting",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "tf": "TensorFlow",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "keras": "Keras",
    "nlp": "Natural Language Processing (NLP)",
    "natural language processing": "Natural Language Processing (NLP)",
    "cv": "Computer Vision",
    "computer vision": "Computer Vision",
    "genai": "Generative AI",
    "gen ai": "Generative AI",
    "generative ai": "Generative AI",
    "llm": "Large Language Models (LLMs)",
    "llms": "Large Language Models (LLMs)",
    "large language models": "Large Language Models (LLMs)",
    "k8s": "Kubernetes",
    "kubernetes": "Kubernetes",
    "docker": "Docker",
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "Google Cloud Platform",
    "google cloud": "Google Cloud Platform",
    "azure": "Microsoft Azure",
    "microsoft azure": "Microsoft Azure",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "ci cd": "CI/CD",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "linux": "Linux",
    "git": "Git",
    "github": "Git",
    "dsa": "DSA",
    "data structures": "Data Structures",
    "algorithms": "Algorithms",
    "dbms": "DBMS",
    "database": "DBMS",
    "databases": "DBMS",
    "os": "Operating Systems",
    "operating systems": "Operating Systems",
    "cn": "Computer Networks",
    "computer networks": "Computer Networks",
    "networking": "Networking",
    "oop": "OOP",
    "oops": "OOP",
    "object oriented programming": "OOP",
    "system design": "System Design",
    "rest api": "REST APIs",
    "rest apis": "REST APIs",
    "restful api": "REST APIs",
    "restful apis": "REST APIs",
    "graphql": "GraphQL",
    "html": "HTML",
    "html5": "HTML",
    "css": "CSS",
    "css3": "CSS",
    "tailwind": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "python": "Python",
    "py": "Python",
    "java": "Java",
    "cpp": "C++",
    "c++": "C++",
    "c#": "C#",
    "csharp": "C#",
    "golang": "Go",
    "go": "Go",
    "rust": "Rust",
    "mern": "MERN Stack",
    "mern stack": "MERN Stack",
    "mean": "MEAN Stack",
}

CANONICAL_SKILL_MAP = SKILL_NORMALIZATION_MAP

def normalize_skill_name(skill: str) -> str:
    """Normalize a skill name string using canonical lookup or title case fallback"""
    if not skill or not isinstance(skill, str):
        return ""
    cleaned = skill.strip().lower()
    return SKILL_NORMALIZATION_MAP.get(cleaned, skill.strip())

