import { CheckCircle2, Download, Award, ShieldCheck, Lock, Clock, Briefcase, Code, Users, MessageSquare } from "lucide-react";
import toast from "react-hot-toast";

export default function RecruiterDecision({
  decision = null,
  roundRecommendations = [],
  candidateName = "Candidate",
  targetRole = "Software Development Engineer (SDE)",
  skills = [],
}) {
  const hasDecision = decision && decision.recommendation;

  const handleDownloadPDF = () => {
    toast.loading("Generating printable interview report...", { duration: 1500 });
    setTimeout(() => {
      window.print();
    }, 800);
  };

  const handleSaveDecision = () => {
    toast.success(`Recruiter decision for "${targetRole}" saved to profile! 🎉`);
  };

  if (!hasDecision && (!roundRecommendations || roundRecommendations.length === 0)) {
    return (
      <div className="bg-white/5 border border-yellow-500/20 rounded-3xl p-6 backdrop-blur-xl">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6">
          <div className="flex items-center gap-3">
            <div className="h-12 w-12 rounded-xl bg-white/[0.05] border border-white/10 flex items-center justify-center">
              <Award className="text-gray-400" size={24} />
            </div>

            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-2xl font-black text-white">Recruiter Decision & Hiring Offer</h2>
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-white/[0.05] text-gray-400 font-bold border border-white/10 flex items-center gap-1">
                  <Briefcase size={11} /> {targetRole}
                </span>
              </div>
              <p className="text-gray-400 text-sm">
                Generated by AI after completing interview rounds for this role
              </p>
            </div>
          </div>

          <div>
            <span className="px-4 py-2 rounded-2xl bg-white/[0.05] text-gray-400 font-semibold text-xs md:text-sm border border-white/10 flex items-center gap-2">
              <Lock size={16} />
              Awaiting Round Completion
            </span>
          </div>
        </div>

        <div className="bg-[#0A0A0A] rounded-2xl p-8 border border-yellow-500/10 text-center flex flex-col items-center justify-center min-h-[160px]">
          <div className="h-12 w-12 rounded-full bg-white/[0.03] border border-yellow-500/10 flex items-center justify-center mb-3">
            <Clock className="text-yellow-400/40" size={22} />
          </div>
          <h3 className="text-base font-bold text-white mb-1">
            Interview in Progress for {targetRole}
          </h3>
          <p className="text-xs text-gray-500 max-w-md">
            Complete Round 1 (Technical), Round 2 (Managerial), and Round 3 (HR Discussion) above. AI will analyze your performance across all rounds and generate your official Hiring Recommendation & Fit Report.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white/5 border border-yellow-500/20 rounded-3xl p-6 backdrop-blur-xl">
      {/* Top Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6">
        <div className="flex items-center gap-3">
          <div className="h-12 w-12 rounded-xl bg-yellow-500/20 flex items-center justify-center">
            <Award className="text-yellow-400" size={26} />
          </div>

          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-2xl font-black text-white">AI Recruiter Decision & Offer</h2>
              {decision?.fitBadge && (
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-green-500/20 text-green-400 font-bold border border-green-500/30">
                  {decision.fitBadge}
                </span>
              )}
            </div>
            <p className="text-gray-400 text-xs md:text-sm flex items-center gap-1.5 mt-0.5">
              <Briefcase size={13} className="text-yellow-400" />
              Role: <span className="text-white font-semibold">{targetRole}</span> • Candidate: <span className="text-white font-semibold">{candidateName}</span>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <span className="px-4 py-2 rounded-2xl bg-green-500/20 text-green-400 font-black text-base md:text-lg border border-green-500/30 flex items-center gap-2 shadow-[0_0_20px_rgba(34,197,94,0.15)]">
            <CheckCircle2 size={20} />
            {decision?.recommendation || "Completed Interview Rounds"}
          </span>
        </div>
      </div>

      {/* 3-Round Scorecard Highlights */}
      {roundRecommendations && roundRecommendations.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5 mb-6">
          {roundRecommendations.map((r) => {
            const isTech = r.round === "ROUND_1_TECHNICAL";
            const isManagerial = r.round === "ROUND_2_MANAGERIAL";
            const Icon = isTech ? Code : isManagerial ? Users : MessageSquare;

            return (
              <div
                key={r.round}
                className="bg-[#0A0A0A] rounded-2xl p-4 border border-yellow-500/10 hover:border-yellow-500/30 transition flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-1.5 font-bold text-xs text-white">
                      <Icon size={15} className="text-yellow-400" />
                      <span>{r.title || r.round.replace(/_/g, " ")}</span>
                    </div>
                    <span className="text-xs font-mono font-bold text-green-400 bg-green-500/10 px-2 py-0.5 rounded border border-green-500/20">
                      {r.score}/10
                    </span>
                  </div>
                  <p className="text-[11px] text-gray-300 line-clamp-3 leading-relaxed mb-2">
                    "{r.keyFeedback}"
                  </p>
                </div>
                <div className="flex items-center gap-1 text-[10px] text-green-400 font-semibold pt-2 border-t border-white/5">
                  <CheckCircle2 size={12} />
                  <span>{r.passed ? "Round Passed & Recommended" : "Completed"}</span>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Grid of Fit Metrics */}
      {decision && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          <div className="bg-[#0A0A0A] rounded-2xl p-4 border border-yellow-500/10 hover:border-yellow-500/30 transition text-center">
            <p className="text-gray-400 text-xs mb-1">Technical Fit</p>
            <p className="text-3xl font-black text-yellow-400 font-mono">
              {decision.technicalFit ?? 85}%
            </p>
            <div className="w-full bg-white/[0.05] rounded-full h-1.5 mt-2 overflow-hidden">
              <div
                className="bg-yellow-400 h-1.5 rounded-full transition-all duration-500"
                style={{ width: `${decision.technicalFit ?? 85}%` }}
              />
            </div>
          </div>

          <div className="bg-[#0A0A0A] rounded-2xl p-4 border border-yellow-500/10 hover:border-yellow-500/30 transition text-center">
            <p className="text-gray-400 text-xs mb-1">Managerial Fit</p>
            <p className="text-3xl font-black text-white font-mono">
              {decision.communicationFit ?? 82}%
            </p>
            <div className="w-full bg-white/[0.05] rounded-full h-1.5 mt-2 overflow-hidden">
              <div
                className="bg-purple-400 h-1.5 rounded-full transition-all duration-500"
                style={{ width: `${decision.communicationFit ?? 82}%` }}
              />
            </div>
          </div>

          <div className="bg-[#0A0A0A] rounded-2xl p-4 border border-yellow-500/10 hover:border-yellow-500/30 transition text-center">
            <p className="text-gray-400 text-xs mb-1">Cultural Fit</p>
            <p className="text-3xl font-black text-white font-mono">
              {decision.culturalFit ?? 88}%
            </p>
            <div className="w-full bg-white/[0.05] rounded-full h-1.5 mt-2 overflow-hidden">
              <div
                className="bg-green-400 h-1.5 rounded-full transition-all duration-500"
                style={{ width: `${decision.culturalFit ?? 88}%` }}
              />
            </div>
          </div>

          <div className="bg-[#0A0A0A] rounded-2xl p-4 border border-yellow-500/10 hover:border-yellow-500/30 transition text-center">
            <p className="text-gray-400 text-xs mb-1">Hiring Confidence</p>
            <p className="text-3xl font-black text-green-400 font-mono">
              {decision.overallHiringConfidence ?? 85}%
            </p>
            <div className="w-full bg-white/[0.05] rounded-full h-1.5 mt-2 overflow-hidden">
              <div
                className="bg-gradient-to-r from-yellow-400 to-green-400 h-1.5 rounded-full transition-all duration-500"
                style={{ width: `${decision.overallHiringConfidence ?? 85}%` }}
              />
            </div>
          </div>
        </div>
      )}

      {/* Recruiter Remarks (AI Generated) */}
      {decision?.remarks && (
        <div className="bg-[#0A0A0A] rounded-2xl p-6 border border-yellow-500/10 mb-6">
          <div className="flex items-center gap-2 mb-2">
            <ShieldCheck className="text-yellow-400" size={20} />
            <h3 className="text-sm md:text-base font-bold text-white">
              Executive Hiring Panel Remarks for {targetRole}
            </h3>
          </div>

          <p className="text-gray-300 text-xs md:text-sm leading-relaxed font-sans">
            "{decision.remarks}"
          </p>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4">
        <button
          onClick={handleDownloadPDF}
          className="flex-1 py-3.5 rounded-xl bg-gradient-to-r from-yellow-300 via-yellow-400 to-yellow-600 text-black font-bold text-xs md:text-sm hover:scale-[1.02] transition flex items-center justify-center gap-2 shadow-[0_0_25px_rgba(255,215,0,0.25)]"
        >
          <Download size={18} />
          Generate & Download Hiring Report (PDF)
        </button>

        <button
          onClick={handleSaveDecision}
          className="flex-1 py-3.5 rounded-xl bg-[#141414] border border-yellow-500/20 text-white font-bold text-xs md:text-sm hover:border-yellow-400 transition flex items-center justify-center gap-2"
        >
          <CheckCircle2 size={18} />
          Save Recruiter Decision
        </button>
      </div>
    </div>
  );
}