import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import API from "../Api";

import AuroraBackground from "../components/background/AuroraBackground";
import AnimatedGrid from "../components/background/GridBackground";
import FloatingParticles from "../components/background/Floating";
import DashboardHeader from "../components/dashboard/DashboardHeader";

import {
  Brain,
  Sparkles,
  TrendingUp,
  AlertCircle,
  Calendar,
  BookOpen,
  Target,
  CheckCircle2,
  ChevronRight,
  ChevronDown,
  RefreshCw,
  ArrowLeft,
  Award,
  Layers,
  Flame,
  ShieldCheck,
} from "lucide-react";

export default function CareerIntelligence() {
  const [userName, setUserName] = useState("Candidate");
  const [learningPlan, setLearningPlan] = useState(null);
  const [weaknesses, setWeaknesses] = useState([]);
  const [candidateProfile, setCandidateProfile] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [expandedDay, setExpandedDay] = useState(1);
  const navigate = useNavigate();

  const fetchCareerData = async () => {
    setIsLoading(true);
    try {
      // 1. Fetch User Profile
      try {
        const userRes = await API.get("/auth/me");
        if (userRes.data?.user) {
          setUserName(userRes.data.user.name || "Candidate");
        }
      } catch (e) {}

      // 2. Fetch Structured Candidate Profile
      try {
        const profileRes = await API.get("/resume/profile");
        if (profileRes.data?.candidateProfile) {
          setCandidateProfile(profileRes.data.candidateProfile);
        }
      } catch (e) {}

      // 3. Fetch Learning Plans
      try {
        const learningRes = await API.get("/learning");
        if (learningRes.data?.learningPlan) {
          setLearningPlan(learningRes.data.learningPlan);
        }
      } catch (e) {}

      // 4. Fetch Candidate Weaknesses & Strengths
      try {
        const weakRes = await API.get("/learning/weaknesses");
        if (weakRes.data?.weaknesses) {
          setWeaknesses(weakRes.data.weaknesses);
        }
      } catch (e) {}
    } catch (err) {
      console.error("Career data fetch error:", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchCareerData();
  }, []);

  const handleGenerateFreshPlan = async () => {
    setIsGenerating(true);
    try {
      const res = await API.post("/learning/generate-plan", {
        targetRole: candidateProfile?.targetRoles?.[0] || "Software Development Engineer (SDE)",
      });
      if (res.data?.learningPlan) {
        setLearningPlan(res.data.learningPlan);
        toast.success("Fresh personalized study roadmap generated by Career Coach Agent! 🎯");
      }
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to generate plan");
    } finally {
      setIsGenerating(false);
    }
  };

  const readinessScore = learningPlan?.readinessScore || candidateProfile?.overallReadinessScore || 74;

  return (
    <div className="relative bg-[#050505] text-white overflow-hidden min-h-screen">
      <AuroraBackground />
      <AnimatedGrid />
      <FloatingParticles />

      <div className="relative z-10 p-4 md:p-6 lg:p-8">
        <div className="max-w-7xl mx-auto space-y-6">
          {/* Header & Back to Dashboard */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={() => navigate("/dashboard")}
                className="p-2.5 rounded-xl bg-white/5 border border-yellow-500/20 hover:border-yellow-400 text-gray-300 hover:text-white transition flex items-center gap-1 text-xs font-semibold"
              >
                <ArrowLeft size={16} />
                <span>Dashboard</span>
              </button>
              <div>
                <h1 className="text-2xl md:text-3xl font-black text-white flex items-center gap-2">
                  <span>AI Career Intelligence</span>
                  <span className="text-xs px-2.5 py-0.5 rounded-full bg-yellow-500/20 text-yellow-300 border border-yellow-500/30 font-mono">
                    Agent Powered
                  </span>
                </h1>
                <p className="text-xs text-gray-400">
                  Personalized performance synthesis, weakness memory tracking, and multi-day study roadmap
                </p>
              </div>
            </div>

            <button
              type="button"
              onClick={handleGenerateFreshPlan}
              disabled={isGenerating}
              className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-yellow-500 to-yellow-600 hover:from-yellow-400 hover:to-yellow-500 text-black font-bold text-xs flex items-center gap-2 shadow-[0_0_20px_rgba(255,215,0,0.3)] transition disabled:opacity-50"
            >
              <RefreshCw size={14} className={isGenerating ? "animate-spin" : ""} />
              <span>{isGenerating ? "Synthesizing Roadmap..." : "Regenerate AI Study Plan"}</span>
            </button>
          </div>

          {/* Top Row: Readiness Score Card & Profile Insights */}
          <div className="grid md:grid-cols-3 gap-6 items-stretch">
            {/* Readiness Gauge Card */}
            <div className="bg-white/5 border border-yellow-500/20 rounded-3xl p-6 backdrop-blur-xl flex flex-col justify-between">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2 text-yellow-400 font-bold text-sm">
                  <Flame size={18} />
                  <span>Interview Readiness Index</span>
                </div>
                <span className="text-[11px] px-2 py-0.5 rounded-full bg-yellow-500/10 text-yellow-300 font-mono">
                  Live Benchmark
                </span>
              </div>

              <div className="flex items-center gap-4 my-2">
                <div className="relative h-24 w-24 rounded-full border-4 border-yellow-500/20 flex items-center justify-center bg-black/40">
                  <div className="text-center">
                    <span className="text-3xl font-black text-yellow-400 font-mono">{readinessScore}</span>
                    <span className="text-[10px] block text-gray-400 font-bold">%</span>
                  </div>
                </div>
                <div className="space-y-1">
                  <h4 className="text-sm font-bold text-white">
                    {readinessScore >= 80 ? "Offer Ready 🏆" : readinessScore >= 65 ? "Solid Foundation 📈" : "Needs Targeted Drills 🎯"}
                  </h4>
                  <p className="text-xs text-gray-400 leading-relaxed">
                    Based on your responses, technical accuracy, and concept mastery across interview rounds.
                  </p>
                </div>
              </div>

              <div className="pt-3 border-t border-white/10 text-[11px] text-gray-400 flex items-center justify-between">
                <span>Target Role:</span>
                <span className="text-yellow-300 font-semibold">{candidateProfile?.targetRoles?.[0] || "Software Engineer (SDE)"}</span>
              </div>
            </div>

            {/* Candidate Memory Weakness Summary */}
            <div className="bg-white/5 border border-yellow-500/20 rounded-3xl p-6 backdrop-blur-xl md:col-span-2 flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2 text-yellow-400 font-bold text-sm">
                    <Brain size={18} />
                    <span>Candidate Memory & Weakness Tracker</span>
                  </div>
                  <span className="text-xs text-gray-400">
                    {weaknesses.length} Logged Concept Weaknesses
                  </span>
                </div>
                <p className="text-xs text-gray-400 mb-3">
                  NexHire AI stores historical concept gaps across your interviews to automatically calibrate future interview plans and reassessments.
                </p>

                {weaknesses.length === 0 ? (
                  <div className="bg-[#0A0A0A] rounded-2xl p-4 border border-yellow-500/10 text-center text-xs text-gray-400">
                    No persistent weaknesses logged yet. Complete interview rounds to populate memory telemetry.
                  </div>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 max-h-[140px] overflow-y-auto scrollbar-thin pr-1">
                    {weaknesses.map((w, idx) => (
                      <div
                        key={idx}
                        className="bg-[#0A0A0A] p-2.5 rounded-xl border border-red-500/20 flex flex-col justify-between gap-1"
                      >
                        <div className="flex items-center justify-between">
                          <span className="text-xs font-bold text-red-300 truncate">{w.topic}</span>
                          <span className="text-[10px] font-mono px-1.5 py-0.2 rounded bg-red-500/10 text-red-400">
                            {w.score}/10
                          </span>
                        </div>
                        <p className="text-[11px] text-gray-400 truncate">{w.concept || w.evidence}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {learningPlan?.nextInterviewStrategy && (
                <div className="mt-3 p-2.5 rounded-xl bg-yellow-500/10 border border-yellow-500/20 text-xs text-yellow-300 flex items-center gap-2">
                  <Target size={14} className="flex-shrink-0" />
                  <span className="truncate">
                    <strong>Next Strategy:</strong> {learningPlan.nextInterviewStrategy}
                  </span>
                </div>
              )}
            </div>
          </div>

          {/* Skill Proficiency Radar & Strengths */}
          {candidateProfile?.skills && candidateProfile.skills.length > 0 && (
            <div className="bg-white/5 border border-yellow-500/20 rounded-3xl p-6 backdrop-blur-xl">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <div className="h-8 w-8 rounded-lg bg-yellow-500/20 flex items-center justify-center text-yellow-400">
                    <Layers size={16} />
                  </div>
                  <div>
                    <h3 className="text-base font-bold text-white">Parsed Skill Proficiency Radar</h3>
                    <p className="text-xs text-gray-400">Extracted from resume & verified through AI interview turns</p>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">
                {candidateProfile.skills.map((skill, index) => (
                  <div
                    key={index}
                    className="bg-[#0A0A0A] p-3 rounded-2xl border border-yellow-500/10 hover:border-yellow-400/40 transition"
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-xs font-bold text-white truncate">{skill.name}</span>
                    </div>
                    <div className="flex items-center justify-between text-[11px] text-gray-400 mb-1.5">
                      <span className="capitalize text-yellow-400/80">{skill.level || "intermediate"}</span>
                      <span className="font-mono text-gray-300">{Math.round((skill.confidence || 0.8) * 100)}%</span>
                    </div>
                    <div className="w-full bg-white/[0.05] rounded-full h-1.5 overflow-hidden">
                      <div
                        className="bg-gradient-to-r from-yellow-400 to-yellow-600 h-1.5 rounded-full"
                        style={{ width: `${Math.round((skill.confidence || 0.8) * 100)}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Interactive Multi-Day Study Roadmap */}
          <div className="bg-white/5 border border-yellow-500/20 rounded-3xl p-6 backdrop-blur-xl">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-xl bg-yellow-500/20 flex items-center justify-center text-yellow-400">
                  <Calendar size={22} />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-white">Personalized 5-Day Study Roadmap</h2>
                  <p className="text-xs text-gray-400">
                    Curated daily milestones generated by Career Coach Agent grounded in your exact interview gaps
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <span className="text-xs px-3 py-1 rounded-full bg-white/5 border border-white/10 text-yellow-300 font-semibold">
                  5-Day Adaptive Plan
                </span>
              </div>
            </div>

            {/* Daily Roadmap Timeline Accordion */}
            <div className="space-y-3">
              {(learningPlan?.dailyRoadmap || []).map((milestone) => {
                const isExpanded = expandedDay === milestone.day;
                return (
                  <div
                    key={milestone.day}
                    className={`rounded-2xl border transition-all duration-300 overflow-hidden ${
                      isExpanded
                        ? "bg-[#0A0A0A] border-yellow-400/50 shadow-[0_0_25px_rgba(255,215,0,0.1)]"
                        : "bg-[#0A0A0A]/60 border-yellow-500/10 hover:border-yellow-500/30"
                    }`}
                  >
                    <button
                      type="button"
                      onClick={() => setExpandedDay(isExpanded ? null : milestone.day)}
                      className="w-full p-4 flex items-center justify-between text-left"
                    >
                      <div className="flex items-center gap-3">
                        <div className="h-8 w-8 rounded-xl bg-yellow-500/20 text-yellow-400 font-mono font-bold text-xs flex items-center justify-center flex-shrink-0">
                          D{milestone.day}
                        </div>
                        <div>
                          <h4 className="text-sm font-bold text-white">{milestone.title}</h4>
                          <p className="text-xs text-yellow-400/80 font-medium">{milestone.focusArea}</p>
                        </div>
                      </div>

                      <div className="flex items-center gap-3">
                        <span className="text-[11px] text-gray-400 hidden sm:inline-block">
                          {milestone.concepts?.length || 0} Concepts • {milestone.practiceQuestions?.length || 0} Drills
                        </span>
                        {isExpanded ? <ChevronDown size={18} className="text-yellow-400" /> : <ChevronRight size={18} className="text-gray-400" />}
                      </div>
                    </button>

                    {isExpanded && (
                      <div className="p-4 pt-0 border-t border-white/5 space-y-4">
                        {/* Concepts Grid */}
                        <div>
                          <h5 className="text-xs font-bold text-gray-300 mb-2 flex items-center gap-1.5">
                            <BookOpen size={14} className="text-yellow-400" />
                            <span>Core Concepts to Master</span>
                          </h5>
                          <div className="flex flex-wrap gap-2">
                            {milestone.concepts?.map((c, i) => (
                              <span
                                key={i}
                                className="px-2.5 py-1 rounded-lg bg-yellow-500/10 border border-yellow-500/20 text-yellow-300 text-xs font-mono"
                              >
                                {c}
                              </span>
                            ))}
                          </div>
                        </div>

                        {/* Practice Questions */}
                        <div>
                          <h5 className="text-xs font-bold text-gray-300 mb-2 flex items-center gap-1.5">
                            <CheckCircle2 size={14} className="text-green-400" />
                            <span>Recommended Practice Drills</span>
                          </h5>
                          <div className="space-y-2">
                            {milestone.practiceQuestions?.map((q, i) => (
                              <div
                                key={i}
                                className="p-3 rounded-xl bg-white/[0.02] border border-white/10 text-xs text-gray-300 flex items-start gap-2"
                              >
                                <span className="text-yellow-400 font-bold font-mono">#{i + 1}</span>
                                <span>{q}</span>
                              </div>
                            ))}
                          </div>
                        </div>

                        {/* Resources */}
                        {milestone.resources && milestone.resources.length > 0 && (
                          <div className="pt-2">
                            <h5 className="text-xs font-bold text-gray-400 mb-1">Recommended References:</h5>
                            <p className="text-xs text-gray-400 font-mono">
                              {milestone.resources.join(" • ")}
                            </p>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
