import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import {
  RefreshCw,
  Flame,
  Target,
  Map,
} from "lucide-react";
import toast from "react-hot-toast";
import API from "../Api";
import { useInterview } from "../context/InterviewContext";
import CareerRoadmap from "../components/career/CareerRoadmap";
import SkillGap from "../components/career/SkillGap";

export default function CareerCoach() {
  const navigate = useNavigate();
  const location = useLocation();
  const {
    currentRole,
    candidateProfile,
    learningPlan,
    setLearningPlan,
    weaknesses,
    confirmedSkills,
  } = useInterview();

  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState("roadmap");

  useEffect(() => {
    if (location.pathname.includes("/skills")) {
      setActiveTab("skills");
    } else {
      setActiveTab("roadmap");
    }
  }, [location.pathname]);

  const handleGenerateFreshPlan = async () => {
    setIsGenerating(true);
    try {
      const res = await API.post("/learning/generate-plan", {
        targetRole: currentRole || "Software Development Engineer (SDE)",
      });
      if (res.data?.learningPlan) {
        setLearningPlan(res.data.learningPlan);
        toast.success("Fresh personalized study roadmap generated by Career Coach Agent! 🎯");
      }
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to generate study plan");
    } finally {
      setIsGenerating(false);
    }
  };

  const readinessScore =
    learningPlan?.readinessScore ?? candidateProfile?.overallReadinessScore ?? null;

  // Extract focus topics from weaknesses or learning plan
  const focusAreas =
    learningPlan?.focusAreas?.length > 0
      ? learningPlan.focusAreas
      : weaknesses?.length > 0
      ? Array.from(new Set(weaknesses.map((w) => w.topic || w.concept).filter(Boolean))).slice(0, 4)
      : [];

  return (
    <div className="space-y-6 pb-16">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-black text-white flex items-center gap-2.5">
            <span>Career Coach & Study Engine</span>
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-yellow-500/15 text-yellow-400 font-mono border border-yellow-500/20">
              Agentic Coach
            </span>
          </h1>
          <p className="text-xs sm:text-sm text-gray-400 mt-1">
            AI-synthesized multi-day study roadmap and skill-gap remediation grounded in your interview turns.
          </p>
        </div>

        <button
          type="button"
          onClick={handleGenerateFreshPlan}
          disabled={isGenerating}
          className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-yellow-300 via-yellow-400 to-yellow-600 text-black font-bold text-xs flex items-center gap-2 shadow-[0_0_20px_rgba(255,215,0,0.25)] hover:scale-[1.02] transition disabled:opacity-50 self-start sm:self-auto"
        >
          <RefreshCw size={14} className={isGenerating ? "animate-spin" : ""} />
          <span>{isGenerating ? "Synthesizing Roadmap..." : "Regenerate AI Study Plan"}</span>
        </button>
      </div>

      {/* Top Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-stretch">
        {/* Readiness Index */}
        <div className="bg-[#0A0A0A] border border-yellow-500/20 rounded-3xl p-6 backdrop-blur-xl flex flex-col justify-between">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2 text-yellow-400 font-bold text-xs">
              <Flame size={16} />
              <span>Interview Readiness</span>
            </div>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-yellow-500/10 text-yellow-300">
              Benchmark
            </span>
          </div>

          <div className="flex items-center gap-4 my-2">
            <div className="h-20 w-20 rounded-full border-4 border-yellow-500/20 flex items-center justify-center bg-black/40 flex-shrink-0">
              <span className="text-2xl font-black text-yellow-400 font-mono">
                {readinessScore !== null ? `${readinessScore}%` : "--%"}
              </span>
            </div>
            <div className="space-y-1">
              <h4 className="text-xs font-bold text-white">
                {readinessScore !== null
                  ? readinessScore >= 80
                    ? "Offer Ready 🏆"
                    : readinessScore >= 65
                    ? "Solid Foundation 📈"
                    : "Targeted Drills Needed 🎯"
                  : "Complete Interview to Score"}
              </h4>
              <p className="text-[11px] text-gray-400 leading-relaxed">
                Calibrated against evaluated turns for {currentRole}.
              </p>
            </div>
          </div>

          <div className="pt-3 border-t border-white/5 text-[11px] text-gray-400 flex items-center justify-between">
            <span>Target Goal:</span>
            <span className="text-yellow-400 font-semibold">{currentRole}</span>
          </div>
        </div>

        {/* Next Strategy */}
        <div className="bg-[#0A0A0A] border border-yellow-500/20 rounded-3xl p-6 backdrop-blur-xl md:col-span-2 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2 text-yellow-400 font-bold text-xs">
                <Target size={16} />
                <span>Next Interview Strategy</span>
              </div>
              <span className="text-xs text-gray-400 font-mono">
                {weaknesses.length} Tracked Memory Gaps
              </span>
            </div>

            <p className="text-xs sm:text-sm text-gray-200 leading-relaxed">
              {learningPlan?.nextInterviewStrategy ||
                "Complete an interview round or click 'Regenerate AI Study Plan' above to formulate a personalized coaching strategy."}
            </p>
          </div>

          {focusAreas.length > 0 ? (
            <div className="pt-3 border-t border-white/5 flex flex-wrap items-center gap-2 text-xs">
              <span className="text-gray-400">Target Focus Areas:</span>
              {focusAreas.map((tag) => (
                <span
                  key={tag}
                  className="px-2.5 py-0.5 rounded-lg bg-yellow-500/10 border border-yellow-500/20 text-yellow-300 text-[11px] font-mono"
                >
                  {tag}
                </span>
              ))}
            </div>
          ) : (
            <div className="pt-3 border-t border-white/5 text-xs text-gray-500">
              Focus areas will be extracted from your interview turns.
            </div>
          )}
        </div>
      </div>

      {/* Sub-tab Switcher */}
      <div className="bg-[#0A0A0A] border border-yellow-500/15 rounded-2xl p-2 backdrop-blur-xl flex items-center gap-2 max-w-xs">
        <button
          type="button"
          onClick={() => {
            setActiveTab("roadmap");
            navigate("/career");
          }}
          className={`flex-1 py-2 px-3 rounded-xl text-xs font-bold transition flex items-center justify-center gap-2 ${
            activeTab === "roadmap"
              ? "bg-yellow-500/20 text-yellow-300 border border-yellow-400/40 shadow-[0_0_15px_rgba(255,215,0,0.15)]"
              : "text-gray-400 hover:text-white"
          }`}
        >
          <Map size={14} />
          <span>5-Day Roadmap</span>
        </button>

        <button
          type="button"
          onClick={() => {
            setActiveTab("skills");
            navigate("/career/skills");
          }}
          className={`flex-1 py-2 px-3 rounded-xl text-xs font-bold transition flex items-center justify-center gap-2 ${
            activeTab === "skills"
              ? "bg-yellow-500/20 text-yellow-300 border border-yellow-400/40 shadow-[0_0_15px_rgba(255,215,0,0.15)]"
              : "text-gray-400 hover:text-white"
          }`}
        >
          <Target size={14} />
          <span>Skill Gaps</span>
        </button>
      </div>

      {/* Sub-tab Content */}
      <div className="space-y-6">
        {activeTab === "roadmap" && (
          <div className="bg-[#0A0A0A] border border-yellow-500/20 rounded-3xl p-6 sm:p-8 backdrop-blur-xl space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-base sm:text-lg font-bold text-white">
                  Personalized 5-Day Study Roadmap
                </h2>
                <p className="text-xs text-gray-400 mt-0.5">
                  Curated daily milestones generated by Career Coach Agent to fortify exact concept omissions.
                </p>
              </div>
              <span className="text-xs px-3 py-1 rounded-full bg-white/5 text-yellow-300 font-mono">
                Adaptive
              </span>
            </div>

            <CareerRoadmap dailyRoadmap={learningPlan?.dailyRoadmap || []} />
          </div>
        )}

        {activeTab === "skills" && (
          <SkillGap
            targetRole={currentRole}
            weaknesses={weaknesses}
            confirmedSkills={confirmedSkills}
          />
        )}
      </div>
    </div>
  );
}
